json.extract! resource,
              :asking_currency,
              :asking_price,
              :condition,
              :created_at,
              :is_borrowable,
              :is_playable,
              :is_purchaseable,
              :is_tradeable,
              :playable_name,
              :playable_type,
              :updated_at,
              :version_name
